### ISSUE TITLE
Data Structure for Animal Modell

### ISSUE THREAD

**Issue by chopmann** [chopmann/Prog-Aufgabe1#8]
@benjaminfoo 
Each Animal has a Unique Incrementing ID, so instead of using a linked list we could use a TreeMap. Deletion right now is O(n) and Insertion O(1). Using a TreeMap for the Animals would make the simulation run faster.

**Comment by benjaminfoo** [comment]
That's right but this is some kind of micro optimization. The focus should be updating the UI while calculating the simulation. However, both things doesn't hurt : )

**Comment by chopmann** [comment]
Wont do :smirk_cat:
